import type { Metadata } from 'next'
import { Open_Sans } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import { GoogleOAuthProvider } from '@react-oauth/google';

import Navigation from './components/navigation';

const open_sans = Open_Sans({ subsets: ['latin'] })

// https://nextjs.org/docs/app/building-your-application/optimizing/metadata
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <GoogleOAuthProvider clientId="751923381039-do8cbpk1fljvos3k118r3n1tuscfhllv.apps.googleusercontent.com">
    <html lang="en">
      <body className={open_sans.className + " container"}>
        <Navigation />
        {children}
      </body>
    </html>
    </GoogleOAuthProvider>
  )
}
