volumes:
  postgres_data:

services:
  api:
    image: api
    build: ./api
    ports:
      - 8000:8000
    command: /commands/api
    env_file:
      - .env/.env.prod
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env/.env.prod
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120

  redis:
    image: redis

  celery_worker:
    build: ./api
    image: celery_worker
    command: celery -A app.worker.celery worker --loglevel=info
    env_file:
      - .env/.env.prod
    depends_on:
      - redis
      - postgres

  celery_beat:
    build: ./api
    image: celery_worker
    command: celery -A app.worker.celery beat -l info
    env_file:
      - .env/.env.prod
    depends_on:
      - redis
      - postgres

  flower:
    image: mher/flower
    command: celery flower --app=app.worker.celery --broker="redis://redis:6379/0"
    env_file:
      - .env/.env.prod
    ports:
      - 5557:5555
    depends_on:
      - redis
      - postgres