"""empty message

Revision ID: 238c17b8d352
Revises:
Create Date: 2024-01-29 21:13:50.085194+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "238c17b8d352"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comic",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rating_enabled", sa.Boolean(), nullable=False),
        sa.Column("pages", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comic")),
    )
    op.create_index(op.f("ix_comic_id"), "comic", ["id"], unique=False)
    op.create_table(
        "user",
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "hashed_password",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
    )
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_table(
        "comicsubs",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("comic_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["comic_id"],
            ["comic.id"],
            name=op.f("fk_comicsubs_comic_id_comic"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_comicsubs_user_id_user")
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "comic_id", name=op.f("pk_comicsubs")
        ),
    )
    op.create_table(
        "openiduser",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user", sa.Integer(), nullable=False),
        sa.Column(
            "openid", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user"], ["user.id"], name=op.f("fk_openiduser_user_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_openiduser")),
    )
    op.create_index(
        op.f("ix_openiduser_id"), "openiduser", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_openiduser_id"), table_name="openiduser")
    op.drop_table("openiduser")
    op.drop_table("comicsubs")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_comic_id"), table_name="comic")
    op.drop_table("comic")
    # ### end Alembic commands ###
