[tool.poetry]
name = "app"
version = "0.1.0"
description = "Archive Binge API"
authors = ["Madeleine Ethridge <madeleine.ethridge@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.104.0"
celery = "^5.3.6"
redis = "^5.0.1"
requests = "^2.31.0"
beautifulsoup4 = "^4.12.2"
lxml = "^4.9.3"

[tool.poetry.group.pytest.dependencies]
pytest = "^7.4.3"
pytest-cov = "^4.1.0"
httpx = "^0.25.1"

[tool.poetry.group.bandit.dependencies]
bandit = { extras = ["toml"], version = "^1.7.5" }

[tool.poetry.group.lint.dependencies]
black = "^23.11.0"
flake8 = "^6.1.0"
isort = "^5.12.0"
mypy = "^1.7.0"
types-requests = "^2.31.0.10"

[tool.poetry.group.dev.dependencies]
tox = "^4.11.3"

[tool.poetry.group.coverage.dependencies]
coverage = "^7.3.2"

[tool.poetry.group.server.dependencies]
uvicorn = { extras = ["standard"], version = "^0.24.0.post1" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.bandit]
exclude_dirs = ["tests"]

[tool.black]
line-length = 79

[tool.isort]
line_length = 79
lines_between_types = 1
profile = "black"
remove_redundant_aliases = true
#skip = ["migrations"]
wrap_length = 79

[tool.mypy]
#plugins = "sqlmypy"
#exclude = "migrations"
show_error_context = true
show_error_codes = true
strict = true

disallow_any_generics = false
disallow_any_unimported = false
disallow_subclassing_any = false
disallow_untyped_defs = true
disallow_untyped_calls = false
ignore_missing_imports = true
no_implicit_optional = true
warn_return_any = true
warn_unused_ignores = true
