---
name: Python application

defaults:
  run:
    working-directory: ./api

on:
  push:
    branches: ["main"]
    paths:
      - api/**/*.py
      - poetry.lock
  pull_request:
    branches: ["main"]
    paths:
      - api/**/*.py
      - poetry.lock
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
          cache: "poetry"

      - name: Install Poetry
        run: pip install poetry==1.7.1

      - name: Install Dependencies
        run: poetry install --without server

      - name: Run Tox (flake8)
        run: poetry run tox -e flake8

      - name: Run Tox (mypy)
        run: poetry run tox -e mypy

      - name: Run Tox (bandit)
        run: poetry run tox -e bandit

      - name: Run Tox (Pytest)
        run: poetry run tox -e pytest

      - name: Coverage Report
        run: poetry run tox -e coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./api/coverage.xml
          flags: pytest
