---
name: Python application

defaults:
  run:
    working-directory: ./api

on:
  push:
    # branches: ["main"]
    paths:
      - api/**/*.py
      - poetry.lock
  pull_request:
    branches: ["main"]
    paths:
      - api/**/*.py
      - poetry.lock
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Install Dependencies
        run: poetry install

      - name: Run Tox (Lint)
        run: poetry run tox -e lint

      - name: Run Tox (Pytest)
        run: poetry run tox -e pytest

      - name: Coverage Report
        run: poetry run tox -e coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: .coverage
          flags: pytest
